#!/usr/bin/env bash
# A little helper script to run BoltCMS on localhost (port 8000) using the PHP (>= v5.4) integrated web server,
# sending the error log to a file named bolt.log, in the current directory, in case something goes wrong.

# Usage:
# Default behaviour:
# $ ./serve

# Known issues: 
# Using the built-in webserver, you will _not_ be able to edit config.yml or .twig files,
# because the built-in server chokes on the URL rewriting. This is a bug in PHP, which they
# apparently do not intend to fix anytime soon. See: https://bugs.php.net/bug.php?id=67671

IP=$(ifconfig -a | grep en0 -A2 | awk '/inet / {print $2}')

php -S $IP:8000 2>> bolt.log

killall php
