// Generated by CoffeeScript 1.10.0
var allow_animations, deleteCookie, getCookie, no_animations, setCookie, switch_language, switch_theme;

setCookie = function(name, value, days) {
  var date, expires;
  if (days) {
    date = new Date();
    date.setTime(date.getTime() + (days * 24 * 60 * 60 * 1000));
    expires = "; expires=" + date.toGMTString();
  } else {
    expires = "";
  }
  return document.cookie = name + "=" + value + expires + "; path=/";
};

getCookie = function(name) {
  var c, ca, i, nameEQ;
  nameEQ = name + "=";
  ca = document.cookie.split(";");
  i = 0;
  while (i < ca.length) {
    c = ca[i];
    while (c.charAt(0) === " ") {
      c = c.substring(1, c.length);
    }
    if (c.indexOf(nameEQ) === 0) {
      return c.substring(nameEQ.length, c.length);
    }
    i++;
  }
  return null;
};

deleteCookie = function(name) {
  return setCookie(name, "", -1);
};

switch_theme = function(target) {
  if (target == null) {
    target = "white";
  }
  $('#theme').attr({
    href: "/css/" + target + ".css"
  });
  $(".theme-button").removeClass('active');
  $("#" + target + "-button").toggleClass('active');
  deleteCookie("style");
  setCookie("style", target, 365);
  return false;
};

switch_language = function(target) {
  var j, lang, languages, len;
  if (target == null) {
    target = "EN";
  }
  languages = ["EN", "FR"];
  for (j = 0, len = languages.length; j < len; j++) {
    lang = languages[j];
    if (lang !== target) {
      $(":lang('" + lang + "')").addClass('hide');
    } else {
      $(":lang('" + lang + "')").removeClass('hide');
    }
  }
  $(".lang-button").removeClass('active');
  $("#" + target + "-button").toggleClass('active');
  deleteCookie("language");
  setCookie("language", target, 365);
  return false;
};

no_animations = function() {
  window.animations = $('html, body, footer').css('transition');
  return $('html, body, footer').css('transition', 'none 0s');
};

allow_animations = function() {
  return $('html, body, footer').css('transition', window.animations);
};

no_animations();

switch_theme(getCookie("style"));

switch_language(getCookie("language"));

setTimeout(allow_animations, 200);
